'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { signUp, supabase } from '@/lib/supabase'

function authMessage(message: string | undefined) {
  const value = message?.toLowerCase() ?? ''
  if (value.includes('already registered') || value.includes('already been registered')) return 'An account with this email already exists.'
  if (value.includes('password')) return 'Choose a stronger password with at least 6 characters.'
  if (value.includes('rate limit')) return 'Too many attempts. Please wait and try again.'
  return 'Unable to create your account. Please try again.'
}

export default function SignupPage() {
  const router = useRouter(); const [fullName, setFullName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false)
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (data.user) router.replace('/landlord/dashboard') }) }, [router])
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const normalizedEmail = email.trim().toLowerCase(); if (!fullName.trim() || !phone.trim() || !normalizedEmail) return setError('Complete all fields.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); if (password !== confirmPassword) return setError('Passwords do not match.'); setLoading(true); try { const { session, error: signUpError } = await signUp(normalizedEmail, password, fullName, phone); if (signUpError) { setError(authMessage(signUpError.message)); return } if (session) { router.replace('/landlord/dashboard'); router.refresh() } else setSuccess(true) } catch { setError('Unable to create your account. Check your connection and try again.') } finally { setLoading(false) } }
  return <main className="min-h-screen bg-gray-50 flex items-center justify-center px-4 py-10"><div className="w-full max-w-md"><header className="text-center mb-8"><Link href="/" className="text-3xl font-bold text-blue-600">Aba Rentals</Link><h1 className="text-2xl font-bold text-gray-900 mt-4">Create your account</h1><p className="text-gray-500 mt-2">List your properties with Aba Rentals</p></header><section className="card p-6">{success ? <div role="status" className="space-y-4"><h2 className="text-lg font-semibold text-gray-900">Check your email</h2><p className="text-gray-600">We sent a confirmation link to <strong>{email}</strong>. Confirm it before signing in.</p><Link href="/auth/login" className="btn-primary inline-block">Go to sign in</Link></div> : <>{error && <p role="alert" className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-4">{error}</p>}<form onSubmit={handleSubmit} className="space-y-4"><div><label htmlFor="fullName" className="label">Full name</label><input id="fullName" value={fullName} onChange={e => setFullName(e.target.value)} className="input" autoComplete="name" required /></div><div><label htmlFor="phone" className="label">Phone number</label><input id="phone" type="tel" value={phone} onChange={e => setPhone(e.target.value)} className="input" autoComplete="tel" required /></div><div><label htmlFor="email" className="label">Email</label><input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} className="input" autoComplete="email" required /></div><div><label htmlFor="password" className="label">Password</label><input id="password" type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} className="input" autoComplete="new-password" minLength={6} required /></div><div><label htmlFor="confirmPassword" className="label">Confirm password</label><div className="flex gap-2"><input id="confirmPassword" type={showPassword ? 'text' : 'password'} value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} className="input" autoComplete="new-password" minLength={6} required /><button type="button" onClick={() => setShowPassword(value => !value)} className="text-sm text-gray-500" aria-label={showPassword ? 'Hide passwords' : 'Show passwords'}>{showPassword ? 'Hide' : 'Show'}</button></div></div><button type="submit" className="btn-primary w-full" disabled={loading}>{loading ? 'Creating account…' : 'Create account'}</button></form><p className="mt-6 text-center text-sm text-gray-600">Already have an account? <Link href="/auth/login" className="text-blue-600 font-medium hover:underline">Sign in</Link></p></>}</section><Link href="/" className="block text-center mt-6 text-sm text-gray-500 hover:text-gray-700">Back to listings</Link></div></main>
}
