'use client'

import { useState, useCallback, useMemo } from 'react'
import { Filters, PropertyType } from '@/lib/types'

interface FilterBarProps { onFilterChange: (filters: Filters) => void }
const ABOLOCATIONS = ['Aba Town', 'Ochie', 'Eziukwu', 'Ariaria', 'Ogbor Hill', 'Asa', 'Umungasi', 'Nkwoagu', 'Umuojima', 'Umuola', 'Aba South', 'Aba North', 'Other']
const PROPERTY_TYPES: PropertyType[] = ['self-contain', 'flat', 'duplex', 'bungalow', 'office', 'shop', 'other']

export default function FilterBar({ onFilterChange }: FilterBarProps) {
  const [showFilters, setShowFilters] = useState(false); const [search, setSearch] = useState(''); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState(''); const [location, setLocation] = useState(''); const [bedrooms, setBedrooms] = useState(''); const [propertyType, setPropertyType] = useState<PropertyType | ''>('')
  const applyFilters = useCallback(() => onFilterChange({ search: search || undefined, minPrice: minPrice ? Number(minPrice) : undefined, maxPrice: maxPrice ? Number(maxPrice) : undefined, location: location || undefined, bedrooms: bedrooms ? Number(bedrooms) : undefined, propertyType: propertyType || undefined }), [search, minPrice, maxPrice, location, bedrooms, propertyType, onFilterChange])
  const clearFilters = () => { setSearch(''); setMinPrice(''); setMaxPrice(''); setLocation(''); setBedrooms(''); setPropertyType(''); onFilterChange({}) }
  const activeFilterCount = useMemo(() => [search, minPrice, maxPrice, location, bedrooms, propertyType].filter(Boolean).length, [search, minPrice, maxPrice, location, bedrooms, propertyType])
  return <div className="card mb-8 p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><label htmlFor="listing-search" className="sr-only">Search listings</label><input id="listing-search" type="search" placeholder="Search areas, homes, or keywords" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) applyFilters() }} className="input pr-4" /></div><div className="flex gap-2"><button onClick={() => { applyFilters(); setShowFilters(true) }} className="btn-primary flex-1 sm:flex-none">Search</button><button onClick={() => setShowFilters(!showFilters)} className="btn-outline relative flex-1 sm:flex-none">Filters{activeFilterCount > 0 && <span className="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-accent text-xs font-bold text-accent-foreground">{activeFilterCount}</span>}</button></div></div>{showFilters && <div className="mt-4 grid grid-cols-1 gap-4 border-t border-border pt-4 sm:grid-cols-2 lg:grid-cols-5"><div><label className="label" htmlFor="min-price">Min price (₦)</label><input id="min-price" type="number" placeholder="Any" value={minPrice} onChange={e => setMinPrice(e.target.value)} className="input" /></div><div><label className="label" htmlFor="max-price">Max price (₦)</label><input id="max-price" type="number" placeholder="Any" value={maxPrice} onChange={e => setMaxPrice(e.target.value)} className="input" /></div><div><label className="label" htmlFor="location">Location</label><select id="location" value={location} onChange={e => setLocation(e.target.value)} className="input"><option value="">All areas</option>{ABOLOCATIONS.map(loc => <option key={loc} value={loc}>{loc}</option>)}</select></div><div><label className="label" htmlFor="bedrooms">Bedrooms</label><select id="bedrooms" value={bedrooms} onChange={e => setBedrooms(e.target.value)} className="input"><option value="">Any</option>{[1, 2, 3, 4, 5, 6].map(n => <option key={n} value={n}>{n}</option>)}</select></div><div><label className="label" htmlFor="property-type">Property type</label><select id="property-type" value={propertyType} onChange={e => setPropertyType(e.target.value as PropertyType)} className="input"><option value="">All types</option>{PROPERTY_TYPES.map(type => <option key={type} value={type}>{type.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())}</option>)}</select></div><div className="sm:col-span-2 lg:col-span-5 lg:flex lg:justify-end"><button onClick={clearFilters} className="btn-outline w-full text-sm lg:w-auto">Clear filters</button></div></div>}</div>
}
