'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { signIn, supabase } from '@/lib/supabase'

function authMessage(message: string | undefined) { if (!message) return 'Unable to sign in. Please try again.'; const value = message.toLowerCase(); if (value.includes('email not confirmed')) return 'Please confirm your email before signing in.'; if (value.includes('invalid login credentials')) return 'Invalid email or password.'; if (value.includes('rate limit')) return 'Too many attempts. Please wait and try again.'; return 'Unable to sign in. Please try again.' }

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { const confirmationError = new URLSearchParams(window.location.search).get('error'); if (confirmationError) setError('The confirmation link is invalid or expired.'); supabase.auth.getUser().then(({ data }) => { if (data.user) router.replace('/landlord/dashboard') }) }, [router])
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const normalizedEmail = email.trim().toLowerCase(); if (!normalizedEmail || !password) return setError('Enter your email and password.'); setLoading(true); try { const { session, error: signInError } = await signIn(normalizedEmail, password); if (signInError || !session) { setError(authMessage(signInError?.message)); return }; router.replace('/landlord/dashboard'); router.refresh() } catch { setError('Unable to sign in. Check your connection and try again.') } finally { setLoading(false) } }
  return <main className="flex min-h-screen items-center justify-center bg-background px-4 py-10"><div className="w-full max-w-md"><div className="mb-8 text-center"><Link href="/" className="text-2xl font-bold tracking-tight text-primary">Aba<span className="text-foreground">Rentals</span></Link><p className="mt-7 text-sm font-semibold uppercase tracking-[0.16em] text-primary">Welcome back</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Sign in to your account</h1><p className="mt-2 text-sm text-muted-foreground">Manage your listings and enquiries in one place.</p></div><section className="card p-5 sm:p-7">{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}<form onSubmit={handleSubmit} className="space-y-5"><div><label htmlFor="email" className="label">Email address</label><input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} className="input" autoComplete="email" required /></div><div><label htmlFor="password" className="label">Password</label><div className="relative"><input id="password" type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} className="input pr-16" autoComplete="current-password" required /><button type="button" onClick={() => setShowPassword(value => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-sm font-semibold text-primary" aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? 'Hide' : 'Show'}</button></div></div><button type="submit" className="btn-primary w-full" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form><p className="mt-6 text-center text-sm text-muted-foreground">Don&apos;t have an account? <Link href="/auth/signup" className="font-semibold text-primary hover:underline">Create one</Link></p></section><Link href="/" className="mt-6 block text-center text-sm font-medium text-muted-foreground hover:text-foreground">← Back to listings</Link></div></main>
}
